version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '3000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    # ports:
    #   - '3000:3000'
    environment:
      - PORT=3000
    # env_file:
    #   - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongo-db:/data/db
    # ports:
    #   - '27017:27017'

  redis:
    image: redis

volumes:
  mongo-db:
