version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '3000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    image: c0san1j/node-app
    # ports:
    #   - '3000:3000'
    environment:
      - PORT=3000
    # env_file:
    #   - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    # ports:
    #   - '27017:27017'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:mypassword@mongo:27017/

  redis:
    image: redis
    volumes:
      - redis-cache:/data

volumes:
  mongo-db:
  redis-cache:
