version: '3'
services:
  nginx:
    ports:
      - '3000:80'
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=Saotome&2338
      - SESSION_SECRET=blackcat
    command: npm run dev
  mongo:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Saotome&2338
